### ISSUE TITLE
Install command creates a `wego-system` Namespace

### ISSUE THREAD

**Issue by sbernheim** [weaveworks/weave-gitops#1005]
**Describe the bug**
The `gitops install` command creates a `wego-system` Namespace on the target cluster into which it installs the Weave GitOps components.  That namespace should be names `gitops-system` instead.

**Environment**
 - gitops: v0.4.0
 - kubernetes:  1.20.6
    - [x] k3s - v1.20.6+k3s1
 - Browser + version: N/A
 -
**Affects versions**

**To Reproduce**
1. install Weave GitOps on any cluster using the `gitops install` command
2. run `kubectl get ns`
3. observe at the `wego-system` Namespace exists and the `gitops-system` namespace does not.
4. experience sadness

**Expected behavior**
The `wego` binary has been renamed to the `gitops` binary so the namespace it creates for the GitOps components it installs should also be renamed from `wego-system` to `gitops-system`.

**Comment by sympatheticmoose** [comment]
@sbernheim thank you for sharing that this is confusing.

 Whilst the CLI is called `gitops` the project is **WE**ave **G**it**O**ps and our directory structure goes under `.weave-gitops` rather than just `gitops`. 

If you weren't previously aware that the binary was called `wego`, do you still feel you would find this confusing? 

We are currently investigating changes to better support existing Flux installations which may (or may not) change our default namespace, and having this feedback is useful.

**Comment by sbernheim** [comment]
I do understand the history, but if we're going to rename the binary from `wego` to `gitops`, we _should_ also rename the Namespace it creates within the cluster.  If I remember correctly, there was some messaging a while back to de-emphasize use of "WeGo" as a nickname for Weave GitOps, and this change would also align with that intention.  Hopefully it's not hard-coded or something and this would be a minor change.

Naming the root configs and/or manifests directory `.weave-gitops` is a reasonable choice.  The namespace could also be `weave-gitops` instead of `gitops-system` - or really any other reasonable name that moves away from the `wego` nickname AFAIC.

I really thought forgetting to change the Namespace name along with the binary was an oversight, and I don't want us to get stuck in a bike-shedding spiral.  If you have a considered reason for keeping the name as `wego-system` go ahead and close this issue without further debate.  I will not be offended.
