### ISSUE TITLE
App Application UI in WGE is very confusing - Change Explainations and Streamline please

### ISSUE THREAD

**Issue by LutzLange** [weaveworks/weave-gitops#1067]
**Describe the bug**
I just tried to add an Application through the UI interface in WGE. There are multiple challenges with it. Let me explain :+1: 

![Screenshot from 2021-11-11 10-13-55](https://user-images.githubusercontent.com/2788194/141271042-f19f2af5-5492-46e5-b2a5-893d49192892.png)

1. Kubernetes Namespace - Field
-- Very confusing. Is this for the App to be put in? Or what should we put into this field? Try and error found that this is the Namespace where flux / our GitOps tooling is installed. So this will always be "wego-system" for WGE. Please remove this field for WGE! Or as a first step change the heading and tell people to not edit this field. It does say "The the target namespace for the application" this is not right.

2. Source Repo URL
-- This has to be the https://github.com/weavegitops/podinfo-app.git Link Please make sure to say so in the description . e.g. https://github.com/$GITORG/$GITREPO'

3. The Config Repo URL
-- It took a while to find out what this might be. It is the Cluster Repository. We are already setting this up at installation time don't we? This should be known in WGE when it is set up. Please put in the default at least. And a drop down if there are multiple Cluster Repositories later so select the right one might be an option. Changing the name to "Cluster Config Repository" might be a good idea.
4.  Path
-- "The path within the git repository where your application YAMLs are stored" is not a good explanation. Are we talking about the Source or the Cluster (aka Config) Repository? Please make sure to say Source Repository.

Additionally, I tried to change my links to https:// but it is broken now. It looks like the changes that "add application" makes are not rolled back on failure.

![Screenshot from 2021-11-11 10-19-55](https://user-images.githubusercontent.com/2788194/141273327-842cb329-38cd-4ce1-920f-a9ce4e17a422.png)

There are multiple issues in the report. And we might want to spin this out into separate issues : 
A) Fix the interface with better commentary ( Kubernetes Namespace, Path, Source Repo URL, Config Repo URL )
B) Get rid of fields for information that is already there ( Kubernetes Namespace + Config Repo URL)
C) On errors all changes should be rolled back. Otherwise we run into residual objects and failure situations.

This was tested on MCCP 0.0.14

**Comment by sympatheticmoose** [comment]
Hi @LutzLange, 

1 - is fixed in main https://github.com/weaveworks/weave-gitops/issues/898 - please take a look and see if you are happy with what I proposed. The namespace refers to where the automation objects will be stored, so even in the case of WGE this can be changed.

2 - Its unclear what you are asking for here... the URL is for the application source repository where your yaml files are located, and can be in the https format or ssh... please can you clarify what you find confusing?

3 - It is not the cluster config directory, it is your gitops repository which can contain multiple clusters. We will be looking at a way that we can inspect how this is set up and have this as readable configuration to have the default behaviour you describe. But in the latest release it was not a required parameter, and you could have as many config repos as you liked. This will be changing and when it does we will be looking to simplify things.

4 - Your application yamls _can_ exist within your config repo, even if this is not recommended as best practice. But as such we cannot make the change you suggest. It is up to the user where they place their application source yaml and this is why it is referenced as such.

I do not believe changing to HTTPS has impacted anything, I believe we convert to SSH format to do the clone. Could you explain more about why you believe something has not rolled back or was it just that the SSH format is in the error message?

I will leave the team to comment on the SSH_KNOWN_HOSTS error you encountered as I've not hit that before.

**Comment by LutzLange** [comment]
Regarding 2: ssh format does not work in my tests. What do I need to make that work? I would need the SSH Private Key in the Cluster, right? Also the git@github.com:weavegitops/podinfo-app.git Link format which is default in Github for ssh now, does not work but that is another bug.

Regarding 3: Is it not best practice to have a GitOps repository that is attached to at least one cluster? And would that not be the default for Weave GitOps Enterpries? 

Regarding 4: Not making a recommendation and leaving room here for doing things that are not best practice are 2 different things. We need to steer people into the best practice direction. If you really want to use your Source Repo as Config repo as well, you can do that. The path however is still referencing the Source repository, that might be used as Config repository as well.

I can't make it work. And converting https:// to ssh:// explains why I can't make it work. It look like I'm missing something in my cluster : 
![Screenshot from 2021-11-11 12-23-03](https://user-images.githubusercontent.com/2788194/141289873-38c36b5b-23f8-457f-9aad-db9356e7f0a5.png)

**Comment by sympatheticmoose** [comment]
2 - As you say there may be a bug with SSH validation on the beta paths, but it _should_ be valid for the source repo URL format, as should the HTTPS format. Which was why I was saying this request doesn't make sense to me:
> This has to be the https://github.com/weavegitops/podinfo-app.git Link Please make sure to say so in the description . e.g. https://github.com/$GITORG/$GITREPO'

3 - Yes you need a repo which stores the automation objects. Enterprise takes this as an install parameter through `gitops upgrade` as I understand, maybe within Enterprise this could be defaulted now. With Core today and the current UI, it is targeting a single cluster and each application you add through this workflow could have a different config repo. A user configurable default is possible, but given the changes planned to install to be more similar to the enterprise experience, that is where we would need to solve this. 

4 - You're right that if you have your application source YAMLs in your config repo, then you are using your application source and config repo as the the same thing. The matching help text for source repo and path I would hope provides at least some guidance, but clearly it has still caused some confusion and we can investigate a change. Perhaps also moving the Path field underneath the source repo, cc @bia

**Comment by foot** [comment]
The error in screenshots has been addressed, there is still stuff here around streamlining

**Comment by sympatheticmoose** [comment]
breaking out moving the path from this issue - #1270
