### ISSUE TITLE
Scanning Helm Repositories

### ISSUE THREAD

**Issue by Himangini** [weaveworks/weave-gitops#1144]
### Description
As suggested [here](https://gist.github.com/bigkevmcd/0ff7197e0a902c3dcde4a1e7bfc3984c#scanning-helmrepositories), we need to create a service which watches HelmRepositories scans for Profiles and caches the result and services the result via the defined APIs.

### Scope
- This applies to Profiles only.
- The Cache needs not persist beyond the lifecycle of the container unless configured otherwise
- Allow the user to specify the cache dir 
- We need to cache the `values.yaml` file 

### Acceptance Criteria
As a developer
I want to scan for profiles and 
I want to cache the result on the file system 
So that I prevent the same profile downloaded multiple times 

### Techincal Notes
- Nice discussion [here](https://weaveworks.slack.com/archives/C01C7FH7EPQ/p1638202268087500)

**Comment by davidstauffer** [comment]
LGTM.

**Comment by aclevername** [comment]
As part of caching we can also consider reducing the cost of interacting with the charts- https://github.com/weaveworks/weave-gitops/pull/1148#discussion_r759540336

**Comment by Himangini** [comment]
Atm, we don't watch ~multiple~ any Helm repository.  The caching mechanism should be implemented keeping in mind that in the future multiple repositories will be watched and we'd cache all of them.

**Comment by Skarlso** [comment]
Caching details:

Some detail about the cache, how it works, and what it caches including the watcher's job in all of this.

# The Watcher ( who watches the watcher? )

The watcher runs as a controller similar to helm-controller. It watches HelmRepositories for changes or creation events. The difference between this and the helm-controller is that we will use the cache and this watcher to notify people about a new version being available for a profile. And we cache the results from the watch. The Watcher is the one fetching the index file and downloading the values file. It does that only when there is a change in the Revision section of the HelmRepository's `Artifact` field. This will prevent us from continuously downloading the same thing over and over again on each request. ( In the tone of Borat ): Is very nice.

# What we cache

We only cache profile related information. That is this thing:

```go
type Profile struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The name of the Profile
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// The URL to a relevant project page, git repo, or contact person
	Home string `protobuf:"bytes,2,opt,name=home,proto3" json:"home,omitempty"`
	// A list of URLs to the source code of this chart
	Sources []string `protobuf:"bytes,3,rep,name=sources,proto3" json:"sources,omitempty"`
	// A one-sentence description of the Profile
	Description string `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	// A list of string keywords
	Keywords []string `protobuf:"bytes,5,rep,name=keywords,proto3" json:"keywords,omitempty"`
	// A list of Maintainers
	Maintainers []*Maintainer `protobuf:"bytes,6,rep,name=maintainers,proto3" json:"maintainers,omitempty"`
	// The URL to an icon file
	Icon string `protobuf:"bytes,7,opt,name=icon,proto3" json:"icon,omitempty"`
	// A map of annotations
	Annotations map[string]string `protobuf:"bytes,8,rep,name=annotations,proto3" json:"annotations,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	// The Kubernetes version
	KubeVersion string `protobuf:"bytes,9,opt,name=kube_version,json=kubeVersion,proto3" json:"kube_version,omitempty"`
	// The Flux HelmRepository
	HelmRepository *HelmRepository `protobuf:"bytes,10,opt,name=helm_repository,json=helmRepository,proto3" json:"helm_repository,omitempty"`
	// A list of available versions
	AvailableVersions []string `protobuf:"bytes,11,rep,name=available_versions,json=availableVersions,proto3" json:"available_versions,omitempty"`
	// The layer of the profile
	Layer string `protobuf:"bytes,12,opt,name=layer,proto3" json:"layer,omitempty"`
}
```

And values. We cache the raw values file which was the thing returned previously by `GetValuesFile` in charts.

# When do we cache

When the watcher's reconcile loop is triggered. In that instance we ALWAYS download and do our thing. We don't check if it has been done already. Why? Because the reconcile is only called in two instances. Create or Update. In either case, we need to do our thing. The reconcile and Kubernetes will take care of detecting changes or new creations. The cache or the reconcile loop doesn't have to worry about that.

# What is given back

Since profiles data is cached, that is what is returned plus values if requested.

# Why disk based cache

Values can be really large. We don't want an in memory cache which could potentially take up megabytes of memory increasing the load on the server pod.

# Invalidating the cache

This doesn't really matter as the cache is constantly updated when there is new data available. We don't ever invalidate manually. The cache basically never expires.

# Architecture of the cache

Cache replaced whatever the profiles endpoint was calling. Which is things in under helm the charts.* methods. Those methods have been all shifted to the Watcher. The watcher is notified on creation and update events regarding ALL HelmRepository objects. Through the Predicate, it's determined if it's a create or an update event. In case of an update if the revision doesn't match, we reconcile.

In case of create we only run the the reconcile if the helmrepository has an artifact. In which case, we do the same thing that has been done before. We call GetCharts with the profiles predicate and the values.

Once that's done, this information is cached. The cache is always recent. It might be that there is a brief period where some information for a profile can't be found if there is no cache for it yet, but in that case the user just refreshes. Chances are that the cache is filled up earlier than the user requesting information about said object.

The following folder structure is used to cache items:

```
➜  helm-cache tree
.
├── cache.lock
└── wego-system
    └── podinfo
        ├── podinfo
        │   └── 6.0.1
        │       └── values.yaml
        └── profiles.yaml
```

The cache.lock is global and not helmnamespace/helmname because there is a scenario where if we are checking that the folder exists before creating, another process creates it, it returns false, and tries to create it and overwrites whatever has been put there. To ensure that it's recent, we always lock. We could use optimistic locking and versioning, but I doubt that, that is needed here.

The top folder is helm-namespace and under it is helm-name. Then followed by a profiles.yaml file which is the yaml marshalled profile information:
```yaml
- available_versions:
  - 6.0.0
  - 6.0.1
  description: Podinfo Helm chart for Kubernetes
  home: https://github.com/stefanprodan/podinfo
  kube_version: '>=1.19.0-0'
  maintainers:
  - email: stefanprodan@users.noreply.github.com
    name: stefanprodan
  name: podinfo
  sources:
  - https://github.com/stefanprodan/podinfo
```

This information is usually small data, so it can sit in a single file. The values is the bigger fish. We save values according to the name of the profile ( which should be unique per helmRepository ( I HOPE ) ) and under that we have folders of versions. And in those versions we'll have a values.yaml file if there are values for that version.

The values file contains whatever was returned before. Which is the full raw value including comments. We already parse that correctly.
