### ISSUE TITLE
Application Environments

### ISSUE THREAD

**Issue by JamWils** [weaveworks/weave-gitops#1230]
## Application Environments

Here is the definition of environments via the [directory structure ADR](https://github.com/weaveworks/weave-gitops-private/blob/main/docs/adrs/0007-directory-layout.md)

> Environment a collection of manifests that adapt an application's manifests for one or more clusters. For example, you might be running the same image, different SQS, and different replicas across clusters. The production-eu and production-us environments run my-org/my-service-image:v0.1.1, but production-us uses another ARN for the SQS queue and increases the number of replicas. Environment manifests are stored in .weave-gitops/apps/<app name>/env/<environment name>/

As a user, I want to be able to deploy applications with slight modifications.  For instance, I want to be able to set the log level based on dev, staging, or production.  Another example, is I want to access different pub sub queues based on locality.  As a user I want to customize my environments in multiple ways whether I use kustomize or helm.

- Create an environment w/o deploying to a cluster (Core)
- Deploy an app environment to a specific cluster (Core)
- Remove an environment from a specific cluster (Core)
- Delete a custom environment for an application (Core)

As a user, I will one day want to control environments via other parameters as well such as branches, tags, or namespaces.  The implementation above shouldn't preclude this capability in the future.

**Comment by palemtnrider** [comment]
Some users will likely have their environment configurations in their application repos and won't want them stored here.  Because of this, we will need a way to have the environment in the gitops-repo point to the environment in the application repo.  One possibility is the environment in the gitops repo patches the GOAT settings for the app.  For example, changing the flux source from the dev branch to a release tag.
