### ISSUE TITLE
Fix buf warnings

### ISSUE THREAD

**Issue by jpellizzari** [weaveworks/weave-gitops#1714]
We get these warnings on `make proto`:

```
Warning: Duplicate generated file name "api/applications/fetch.pb.ts". Buf will continue without error here and drop the second occurrence of this file, but please raise an issue with the maintainer of the plugin.

```

We should try to make those disappear. A version bump or possibly a PR into the project might fix it.

**Comment by yitsushi** [comment]
I think that's the intended behavior. `buf` sends proto files in one-by-one, so `protoc-gen-grpc-gateway-ts` has no knowledge about the whole project, each command execution (generate) knows only one proto file. That's how it works, but because it's optimized for web, it tries to reduce the number of files and size (or something similar), to achieve this `protoc-gen-grpc-gateway-ts` generates `fetch.pb.ts` file at the same location, so only one `fetch.pb.ts` will be generates and saved and all other modules (in our case `applications`, `core`, and `profiles`) are generated to use the same `fetch.pb.ts`.

If we change the behavior, we end up with three `fetch.pb.ts` files with the same content, and because the plugin has no knowledge about how many other files we have, it can't say "I'll not send this file to generate again."

**Comment by yitsushi** [comment]
Ignore that. `buf` has an option to send all files to one process.

> There are two options:
> 
> **directory** (default)
> 
> This results in buf splitting the input files by directory and making separate
> plugin invocations in parallel. That's roughly the concurrent equivalent of
> this operation:
> 
> ```
> $ for dir in $(find . -name '*.proto' -print0 | xargs -0 -n1 dirname | sort | uniq); do
>     protoc -I . $(find "${dir}" -name '*.proto')
> done
> ```
> 
> Almost every protoc plugin either requires this, so this is the recommended
> strategy. The directory strategy is used by default if omitted.
> 
> **all**
> 
> This results in buf making a single plugin invocation with all input files,
> which is roughly equivalent to this:
> 
> ```
> $ protoc -I . $(find . -name '*.proto')
> ```
> 
> This is needed for certain plugins that expect all files to be given at once.


Source: https://docs.buf.build/configuration/v1/buf-gen-yaml#strategy
