### ISSUE TITLE
Figure out what is up with FOSSA

### ISSUE THREAD

**Issue by Callisto13** [weaveworks/weave-gitops#1848]
FOSSA checks are [failing consistently on PRs](https://github.com/weaveworks/weave-gitops/runs/5757470131?check_suite_focus=true) with the delightfully useful error:

```
Error: The process '/opt/hostedtoolcache/fossa-cli/3.1.8/linux/fossa' failed with exit code null
```

Theories so far:
1. Github was down/iffy? Nope, it has been going on long enough that we cannot blame status problems
2. We are on a free tier and ran out of "credits"? Nope, Mazz checked there are no alerts there
3. A version change of something in the action image makes it break?
4. There was an update to the FOSSA action/bin which breaks for us?
5. (add new wild theory here)

FOSSA account details are in the Shared vault.

You could try running the FOSSA binary yourself (if you can get it with our license IDK), or you can run the action with something like [this](https://github.com/mxschmitt/action-tmate) and get a shell into it as it is running.

**Comment by ozamosi** [comment]
So I logged in to fossa, and then I clicked on the "enable github integration" button, and now it's not failing. Now it's however tied to my github account, so the day I leave it'll break again.

**Comment by Callisto13** [comment]
well obviously you can never lead. a blood pact will be sent to you for your signature asap

**Comment by mnowster** [comment]
@ozamosi if you remove it, log in as the shared corp IT account and re-click the button does that work?

**Comment by ozamosi** [comment]
It should be tied to `weave-gitops-bot` now, no blood pact required.

**Comment by ozamosi** [comment]
It seemed to be working, then it stopped working. Today, it worked in [this main branch merge](https://github.com/weaveworks/weave-gitops/actions/runs/2088828659) but then isn't working on [my PR](https://github.com/weaveworks/weave-gitops/runs/5814115824) despite me having tried to re-run it several times. And this is all the runs since last week, so I don't think it's rate limiting. My PR _does_ have a tonne of package(-lock).json changes, though, in case the upload size or package-lock.json version or something that's making it refuse.

**Comment by ozamosi** [comment]
I've not seen failures from this for a while, closing.
