### ISSUE TITLE
Graph does not render on Safari

### ISSUE THREAD

**Issue by steveww** [weaveworks/weave-gitops#2049]
**Describe the bug**
Graph does not render on Safari

**Is this a UI bug or a server bug?**
- [X] UI
- [ ] Server

**What is the severity of the bug**

- [ ] `severity/Critical`: Weave GitOps is crashing, the UI is inaccessible or a key feature is unusable. There is no known workaround.
- [ ] `severity/Major`: Weave Gitops functionality or a key feature is broken. There is a workaround, but the workaround requires significant effort.
- [X] `severity/Minor`: A non-key feature or functionality is broken. There is a fairly straightforward workaround.
- [ ] `severity/Low`: Doesn’t affect primary flow/functionality but would be good to fix.

**Environment**
 - Weave-Gitops Version, commit sha or image tag: [e.g. `v0.1.0`, `3499ba2a`, or `1651069883-3499ba2a2c78a7c04c47c56c58eb77eede4b21f4`]
 - How you deployed the Weave GitOps server: [e.g. Tilt, Helm Chart, etc]
 - Kubernetes version:  [e.g. 1.20.4]
 - Where are you running your cluster?
    - [ ] KinD - _version_
    - [ ] k3s - _version_
    - [X] cloud GKE Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.10-gke.2000", GitCommit:"0823380786b063c3f71d5e7c76826a972e30550d", GitTreeState:"clean", BuildDate:"2022-03-17T09:22:22Z", GoVersion:"go1.16.14b7", Compiler:"gc", Platform:"linux/amd64"}
    - [ ] other - _name_ _version_
 - Browser + version: Safari 15.4

**To Reproduce**

**Expected behavior**

**Config and Logs**
If applicable, add logs to help explain your problem. _please compress the output before attaching_
- [ ] The yaml of the object you are viewing
- [ ] Logs from the `wego-app` pod
- [ ] Events from `flux-system` namespace (Or the namespace you deployed flux and/or Weave GitOps)
- [ ] `kubectl cluster-info dump`
- [ ] Prometheus alerts
- [ ] Flux logs

**Screenshots**

<img width="1440" alt="Screenshot 2022-04-29 at 16 18 26" src="https://user-images.githubusercontent.com/5420958/165974147-5b9cde6c-0cb4-4b0d-ba5b-0929008e335f.png">

**Additional context**

**Comment by jpellizzari** [comment]
I could not get a working WebKit browser on Linux, so someone else will have to take a look at this :frowning:

**Comment by opudrovs** [comment]
@jpellizzari @JamWils 

I can confirm this issue in Safari. It may be a problem with Safari not handling `transform` attribute on labels well in SVG or smth. similar.

So, I could try experimenting with the chart labels in D3.js to change what code is generated for the chart labels. (Although it is not guaranteed it would work, because Safari and some other browsers have problems with rendering later additions to SVG standard in general.)

But I am not able to test the bug locally because of another error. I see the following error in any browser in the local deployment with test payload (based on the dev process guide) and on many pages in the staging:

<img width="1437" alt="Screenshot 2022-05-20 at 16 46 55" src="https://user-images.githubusercontent.com/8824708/169568667-112817ae-b1c4-46c0-9e20-dc0bbdcd9021.png">

Is it a known or a new/temporary issue?

I can only view the graph in staging for the Applications > weave-gitops-apps app. For Applications > flux-system, I see the same error.

**Comment by jpellizzari** [comment]
> Is it a known or a new/temporary issue?

Looks like someone forgot a `?` somewhere.

**Comment by jpellizzari** [comment]
> I can confirm this issue in Safari. It may be a problem with Safari not handling `transform` attribute on labels well in SVG or smth. similar.

This may be down to Safari not supporting `foreignObject` the same way the others do:

https://bugs.webkit.org/show_bug.cgi?id=23113

**Comment by opudrovs** [comment]
@jpellizzari quite possible, that it is related to this bug.

For now I see that there are transform values `transform="translate(-50000,0)"`  applied to SVG groups around foreignObjects in Safari. If I copy correct transform values `-325,-100` from Chrome to Safari elements, the labels return to their proper place.

<img width="1419" alt="graph_safari_transform" src="https://user-images.githubusercontent.com/8824708/169618900-38ed2c59-f816-46a2-9157-e37276748774.png">

<img width="1423" alt="graph_safari_transform_fixed" src="https://user-images.githubusercontent.com/8824708/169618919-7bd3dd9d-1b61-4412-a8c1-f46fdacf1d7c.png">

To try to fix it, I need to be able to test the graph locally. Maybe another label type or some attribute or style override will help.
