### ISSUE TITLE
SPIKE:  Define idempotency requirements for Weave Gitops

### ISSUE THREAD

**Issue by markramm** [weaveworks/weave-gitops#206]
wego add command is a specific instance of this.    This spike should include documenting the inputs/output states for the wego add command, and focus on the near term

Items to consider: 

- Local wego state
- Kubernetes commands
- Git repository changes

**Comment by jrryjcksn** [comment]
# Wego Idempotence
There are three areas to consider when discussing idempotence for Weave GitOps:
* The cluster state
* The git state (potentially in multiple repositories)
* The state of the running UI

For Weave GitOps, we do not require complete idempotence -- only effective idempotence. Specifically, differences that do not affect system behavior do not violate idempotence for our purposes. For example, if an action caused the next UI refresh to display status in a different order, that wouldn't necessarily constitute a violation of idempotence (even though in reality we would likely sort such a list). A more salient example is the `checkpoint` support we will have in our commands. Even though each repeated call to a command might update checkpoint, that should not be considered a failure of idempotence.

# wego gitops install
Since `wego gitops install` is basically a wrapper around `flux install` with a couple of additional manifests (namespace and app CRD), we don't currently have anything to do here. In fact, on a slow machine/network, we already take advantage of the idempotence of `wego install` since rerunning `wego install` will continue the install process and complete it if the initial call timed out.

# wego app add
* cluster state
  Kubernetes ignores updates that do not change resource specs, so we're free to reapply manifests as long as there are no generated names based on external information such as timestamps. With the current approach to manifest generation, the state of the cluster shouldn't be an issue.
* git state
  How we handle the state of the git repositories is a more interesting question. In the "directly commit and push" model, git should show no change when we regenerate equivalent manifests which would be similar to the Kubernetes case. In the PR model, however, we will need to ensure that we generate the same branch name for every PR for the same app. Otherwise, a second call to `wego app add` for the app would generate a distinct PR and the user might or might not have merged or rebased the PR from the previous `wego app add` for the same app. If she had _not_, the new PR could be based on the same commit as the old one and one of them would no longer apply after the other was merged. Plus, it could be argued that just having multiple distinct PRs would violate idempotence in and of itself.

# wego flux
In the case of `wego flux`, we will just get whatever behavior the corresponding flux command provides. There isn't anything we can do about that short of potentially disallowing certain flux commands (assuming there are any that aren't idempotent) and that would defeat the purpose of having `wego flux`.

# other wego commands
For now, none of the other commands change anything, other than potentially the contents of the checkpoint system.
