### ISSUE TITLE
Publish helm charts only when the chart version is changed, rather than every time the chart is changed

### ISSUE THREAD

**Issue by sympatheticmoose** [weaveworks/weave-gitops#2180]
Our current GH action https://github.com/weaveworks/weave-gitops/blob/main/.github/workflows/chart.yaml publishes a new version of the Helm Chart to our Helm Repository after a merge on main to the charts directory. 

Issues can occur when there is a dependency on updates between the server and chart, as one will be published before the other and can result in breakages such as #2171.

Publishing the helm chart should not be absolutely tied to the overall release process - it's possible to upgrade and downgrade the image using the same chart, which is a simple way to try out RCs - use the latest released chart (which is shipped with the most recent stable release), and override the image to the latest version. Therefore, we must be able to make a chart which is compatible with both the current and next release.

At the same time, we shouldn't release-on-merge the chart every single time - we should batch up changes and release them in a orderly and controlled manner.

**AC**
* When the helm chart is changed, it is not automatically released
* When the helm chart version is changed, it is automatically released
* As a developer, when I make a PR that will release the chart, I receive a warning telling me that/what I'm about to release.

**Comment by yitsushi** [comment]
> Issues can occur when there is a dependency on updates between the server and chart, 

There should not be such dependency updates. Chart changes should be independent from server release because people can override the image the use (server version). I know it's their responsibility if they change the image in the values file, but it's not something we don't allow.

Like [in this PR](https://github.com/weaveworks/weave-gitops/pull/2086), we should make chart changes to keep it compatible with previous version. In general PR should contain only Chart or Server related changes, that way we can catch dependency errors (like mentioned in the issue) before merge.

(But that's only my opinion on the topic)

I think we build and publish new chart on merge because that way we can use the latest chart in QA/testing procedures.

**Comment by ozamosi** [comment]
This was done to make the helm chart behaviour match the manual behaviour, as they're both artefacts we're relatively likely to publish more often than - or at least independently of - full releases.

I also think this process is proving more fragile than it should be, and we should improve it.

**Comment by sympatheticmoose** [comment]
> This was done to make the helm chart behaviour match the manual behaviour, as they're both artefacts we're relatively likely to publish more often than - or at least independently of - full releases.

Can you help me understand this a little more? What is it you mean by the "manual behaviour"?

If we were to pursue https://github.com/weaveworks/weave-gitops/issues/1992, would that change anything?

+1 on testing improvements for the helm chart :)

**Comment by ozamosi** [comment]
Manual means multiple things, doesn't it - I meant the behaviour of the manual i.e. docs.gitops.weave.works. Is that why the directory is "website" rather than "manual"? :grin:

**Comment by sympatheticmoose** [comment]
ahhh gotcha

**Comment by JamWils** [comment]
@ozamosi is this something we want to fix?  Or should I close this out?

**Comment by ozamosi** [comment]
I changed the story slightly - rather than "only release chart when releasing core", it now suggests to only release the chart when an action is taken (i.e. the chart version is changed) - this action will be taken by releases, but this action needs to be able to take place at other times too.

This is something I think we want to do.
