### ISSUE TITLE
The event message doesn't get displayed correctly 

### ISSUE THREAD

**Issue by stefanprodan** [weaveworks/weave-gitops#2239]
The event message is trimmed making it impossible to debug reconciliation errors.

<img width="1229" alt="Screenshot 2022-05-30 at 13 32 13" src="https://user-images.githubusercontent.com/3797675/170976304-aefd0472-8e31-43f0-9a5b-6be993da5c8a.png">

**Environment**

- Weave-Gitops Version v0.8.0
- Flux Version v0.30.2
- Kubernetes version v1.23.5

**Expected behavior**

The event message should be rendered on multiple lines respecting the `\n` that Flux injects in the message.

**Actual Behavior**

The event message is trimmed.

**Comment by JamWils** [comment]
Ideally, we can cap the length of that table cell and have multiple lines to truncate the width of the error message so you can clearly read the entire message on the screen as well.

**Comment by JamWils** [comment]
1. @opudrovs yeah that looks good.  We can look at doing more advanced formatting in another iteration to meet the standard's of Stefan's screenshots from Slack.

2. As for this one I provided a screenshot below.  Yes, I would want there to be a max width to the cell and then the error would wrap.

I would expect to see this behavior for all tables that have the message column in the app.

<img width="680" alt="Screen Shot 2022-05-31 at 6 32 17 PM" src="https://user-images.githubusercontent.com/1825111/171294809-b94e3eb4-1f0b-44fd-a057-5aa8917d23ec.png">
d

**Comment by JamWils** [comment]
@stefanprodan thanks for posting those screenshots.  I'll create a follow-up story so we can have these formatted even better in the future.  For now, I want to get you some text wrapping and not have the errors cut off with `this is importa...`.

**Comment by opudrovs** [comment]
@JamWils OK, thanks!

Should we also limit the max height of a message cell too (with adding vertical scroll if the wrapped message is too long)? Or are messages supposed to be relatively short and a message cell will never become too tall?

**Comment by JamWils** [comment]
🤔 I'm less concerned about the height.  Ideally the user can see the error clearly and we don't want to trim it in anyway.  Some of these errors can get long, but wrapping will make it more manageable to view and understand what is going on versus scrolling horizontally endlessly.

**Comment by JamWils** [comment]
@opudrovs in my tired state I realized I put some scope creep on this.  If you think we should address the wrapping of errors in a separate issue then I am 💯.  We should focus on fixing the trim issue first.

**Comment by opudrovs** [comment]
@JamWils it is easy to add wrapping to all message cells with basic CSS styling. It should handle multiline messages and long lines without breaks fine. We'll see if this simple fix is enough. If not, we can refine it in another PR.

**Comment by opudrovs** [comment]
@JamWils I've added support for multiline messages for all message table cells (in the `EventsTable`, `AutomationsTable`, `SourcesTable`, `ReconciledObjectsTable`).

1) The multiline messages and very long single-line messages are supported fine. But now it sometimes auto-breaks shorter messages too:
<img width="1411" alt="Screenshot 2022-06-01 at 12 25 22" src="https://user-images.githubusercontent.com/8824708/171389375-fb8ef2b3-1f03-45ed-88cd-d497ef723ff4.png">

If this behavior is undesirable, we need to specify a min width for the cell/column, in addition to max width (which is not quite working in the project too, but it requires further investigation how the column widths are calculated). Smart auto-wrap doesn't work well in the browser without an explicitly set min-width.

If it's OK, I can submit a PR with auto-wrapping.

2) Some event messages (for example, with long commit names) come already trimmed from the backend:

<img width="1121" alt="Screenshot 2022-06-01 at 12 10 57" src="https://user-images.githubusercontent.com/8824708/171390164-e5ff3edf-08aa-471c-90c5-c7762f2e3bf9.png">

Is it expected behavior?

**Comment by stefanprodan** [comment]
@opudrovs the multi-line formatting looks really good, IMO it's fine to auto-break everywhere.

**Comment by JamWils** [comment]
+100, @opudrovs this looks great, we can always iterate on top of this work if we need to.
