### ISSUE TITLE
Duplicates on detail pages table view

### ISSUE THREAD

**Issue by JamWils** [weaveworks/weave-gitops#2324]
**Describe the bug**

When I go to the detail page for a kustomization or helm release

**Environment**

- Weave-Gitops version: main-624342f
- Flux version: ???
- Kubernetes version: ???

**To Reproduce**

1. Go to the `flux-system` kustomization.
2. Make sure there are kustomizations on the page and you will see duplicates per the screenshot below.

**Expected behavior**

I would expect to not see duplicates.

**Actual Behavior**

There are duplicates.

**Additional Context (screenshots, logs, etc)**

![Screen Shot 2022-06-14 at 9.13.10 AM.png](https://images.zenhubusercontent.com/60f5a90306cf76325d5accdc/19469d74-b784-4484-ae0f-3b9ee8481d21)

**Comment by chanwit** [comment]
I once hit a similar bug in the KS's inventory enumeration.
The logic behind that bug was that there was a query to collect GVKs from the server-side and used each GVK to query resources. There were often duplicated entries in GVKs, so we obtained the same resources in the subsequence queries.

I think this issue is likely the same.
