### ISSUE TITLE
Create new gitops beta run command

### ISSUE THREAD

**Issue by JamWils** [weaveworks/weave-gitops#2355]
As a platform operator, I want to be able to get started with the power of Flux’s reconciliation process quickly.  I don’t know what Flux is capable of.  I don’t know how to “bootstrap” a cluster; and I heard of “GitOps” but really don’t know how to get started.  I want a simple command such as `gitops beta run <filepath>` to get started.

### Acceptance Criteria

When I run `gitops beta run <filepath>`

1. If I don’t have any cluster in my kube config then I will be shown an error.
2. Given I have a valid connection to a cluster when I run the command I expect the command to connect to my currently selected cluster.
3. If I don’t have Flux installed on the cluster then the prerequisites will be installed to initiate the reconciliation process.
    1. This includes all default controllers to set up a reconciliation loop such as the notification-controller, helm-controller, kustomization-controller, and source-controller.
    2. This will also add all relevant CRDs from the controllers above such as Kustomizations, Helm Releases, Git Repository, Helm Repository, Bucket, Alerts, Providers, and Receivers.
4.  Given I have Flux installed on the cluster then we do not need to install flux. 
5. This would be able to work with local (kind and k3d) and remote clusters.

### Out of Scope
1. This just includes installing Flux onto the cluster but does not involve creating the prerequisite reconciliation.
2. This does not include image auto CRDs and controller from Flux.  These are not normally installed by default and will be dealt with in a future story.

**Comment by chanwit** [comment]
I would suggest the command name be `gitops runtime install` or `gitops install-flux` instead of `gitops run`.

**Comment by JamWils** [comment]
Do you think something like `gitops runtime` makes more sense @chanwit?  Also, you have the idea of `install` or `add`.  I was viewing this as a long running process such as `port-forward`.  Is that the wrong approach?  It seems hard to pull this off without some process running on the local machine as well as the cluster.

**Comment by ozamosi** [comment]
See notes in #2363 for how to generate manifests.

**Comment by chanwit** [comment]
I emulated the behavior of gitops run with Tilt and found a gap.
here's the scenario:
  - A Dev had an Nginx program. The dev also had Deployment yaml for nginx.
  - The dev put the deployment yaml into ./dev
  - The dev run `gitops run ./dev`
then the Dev would ask what's next?

The missing puzzle in the above scenario was the port-fwd element (cc @ozamosi)

`gitops run ./dev` should expect a port-fwd parameter for a resource (a Service, a Pod etc)

for example `gitops run ./dev --port=8080 --resource=svc/nginx`

It is a bit hard for this command to "infer" the service name or port number automatically, so the inference capability should be out-of-scope.

**Comment by ozamosi** [comment]
> If I don’t have any cluster in my kube config then I will be shown an error.
> Given I have a valid connection to a cluster when I run the command I expect the command to connect to my currently selected cluster.

Look at `pkg/kubehttp` for `outOfClusterConfig`, which connects to your currently selected cluster. I expect it to error if there isn't one or it can't connect to it. You can test by moving your `.kube/config`.

>If I don’t have Flux installed on the cluster

The version endpoint has code for checking for the installed flux version - if that code fails to find anything, flux isn't installed. It might be that you can't reuse that code as is since it's using our server abstraction for clusters - but the same query should work.

> then the prerequisites will be installed to initiate the reconciliation process. 

See sample code in #2363. It generates the flux manifests that we want to store in the filesystem (store them in `{file-path}/flux-system/gotk-components.yaml`). This code was a quick hack based on https://github.com/fluxcd/flux2/blob/main/cmd/flux/install.go#L118 so have a look at that, too.

Then, that needs to be applied to the running cluster. I don't think we currently do that anywhere (we let flux do it for us), so this'll be new code. The flux install above calls this Apply function: https://github.com/fluxcd/flux2/blob/547e39d24c54235ee2ad8bbec75c5f47c4b82221/internal/utils/apply.go#L41 Because it's stored in `internal` we should not use it directly, but it looks to ultimately be mostly using the `ssa` module which is _not_ internal, so we can call that directly.

> This would be able to work with local (kind and k3d) and remote clusters.

This is handled by the kubehttp client.

---

I don't want to set up integration tests for the whole flow against cloud clusters, so test manually with both kind clusters and e.g. a google cloud cluster. Most of these steps can still be tested one by one.

**Comment by ozamosi** [comment]
Created issue #2405 for port forwarding question
