### ISSUE TITLE
sort events by newest first

### ISSUE THREAD

**Issue by sympatheticmoose** [weaveworks/weave-gitops#2534]
<img width="1676" alt="Screenshot 2022-08-04 at 14 38 48" src="https://user-images.githubusercontent.com/19860021/182861129-eff99505-7cdb-4b4d-adce-5488b985f3eb.png">

Makes it easier to know which events are the ones to care about and also helps when there are a large number of events, where the latest events may be outside of the visible part of the screen

### Acceptance Criteria
* When I go to any events tab it should be sorted by timestamp in descending order by default.
* Sorting by timestamp should also be a secondary sort if we are sorting by another column.  E.g. if I am sorting by `name`, I would expect rows with the same name to be in descending order via timestamp.
* This should be for all `event` tabs on detail pages such as sources, kustomizations, and helm releases.

**Comment by sympatheticmoose** [comment]
@opudrovs FYI, trying on `0.9.3` I'm struggling to get sort by timestamp to alter the display of the data at all

https://user-images.githubusercontent.com/19860021/186162329-a90fdce1-f2b6-4039-b961-8b452cb8105c.mov

**Comment by opudrovs** [comment]
@sympatheticmoose sorting event by timestamp or reason was broken, I discovered it when I started working on the current issue. So, I fixed sorting in #2642 first.

**Comment by sympatheticmoose** [comment]
Awesome 😄 thanks @opudrovs

**Comment by opudrovs** [comment]
@sympatheticmoose np, thanks for reporting it.

**Comment by opudrovs** [comment]
@sympatheticmoose @JamWils the Events table will by sorted by timestamp in reverse order (the earliest events on top) by default, this is clear.

Just to confirm the expected behavior: if I switch to sorting the Events table by another column value (for example, reason) and then switch back to sorting it by timestamp by clicking on the timestamp column header, the default sort direction for the timestamp column should be reverse (earliest events first) too after the switch (not only when sorting initially), correct? Because I will need to make some adjustments to the initial sort direction for this column only.

**Comment by ozamosi** [comment]
Suggestion: negate the sort value.

We're not displaying it as "time" (where a more recent value is bigger), we're displaying it as "age" (where a more recent value is smaller) - so sorting "1 second ago" before "1 hour ago" is the forwards order, not the reverse order.

**Comment by opudrovs** [comment]
@ozamosi interesting suggestion, do you mean to change the it from `sortValue: (e: Event) => e.timestamp,` to smth. like `sortValue: (e: Event) => <now> - e.timestamp,`?

**Comment by ozamosi** [comment]
Exactly - or just `0` instead of `<now>`, because the present has an unfortunate habit of not standing still.

**Comment by opudrovs** [comment]
OK, thanks, will do it! This simplifies things.
