### ISSUE TITLE
Remove Application from one cluster via PR

### ISSUE THREAD

**Issue by markramm** [weaveworks/weave-gitops#256]
As an application operator I would like to be able to run wego application remove [app] to should  not leave workloads running but remove the gitops management, so I can clean up after tests. 

--remove-workload flag is a required flag

Ideally this will issue a PR that removes the customization in .wego to delete the files.   

In the short term this may require an imperative command as well.   

If there is a user initiated clean up step in the short term that must be documented.

**Comment by markramm** [comment]
As an application operator I would like to be able to run` wego application remove [app]` to remove gitops control of that app.  By default this should leave workloads running but remove the gitops management.

**Comment by markramm** [comment]
Clean up UX so people don't get confused between remove and delete.

**Comment by bia** [comment]
How about `delete` and `remove-automation` or `deautomate`  ? `unautomate` ?

**Comment by markramm** [comment]
https://github.com/fluxcd/flux2/discussions/763 has some more information.

**Comment by markramm** [comment]
Remove the app always, and always require the --force flag.

**Comment by jrryjcksn** [comment]
There is no indication (that I have found) in this story what the `--force` flag is supposed to do -- only that it is always required. If it means, "also remove the workloads from the cluster", then I feel it is poorly named. If it means something else, please describe its function.

Also, it is hard to interpret this sentence:

```
As an application operator I would like to be able to run wego application remove [app] to should  not leave workloads running but remove the gitops management, so I can clean up after tests. 
```

In any case, I am currently unable to determine what is being requested here which is why I moved it back to "Refine"

**Comment by markramm** [comment]
Let's change it to --remove-workload

By default it would just remove the automation, and because that is hard, the --remove-workload flag is (for now) always required.

**Comment by JamWils** [comment]
@jrryjcksn and @rokshana-b does this need a QA label?

**Comment by jpellizzari** [comment]
This is open because we don't yet support `remove` via PR.

**Comment by jpellizzari** [comment]
Implementation notes:
* Remove the entry from the `user/kustomization` for a given cluster
* Remove the `apps/<my app>` directory from the gitops repo

**Comment by josecordaz** [comment]
This is the work plan I have in mind for this ticket. Let me know if I should consider something different.

![image.png](https://images.zenhubusercontent.com/606389311ead0cc4788a9a72/b53f969a-b4b1-449d-a01f-53570301af1a) 

In the case where we want to use a PR to avoid the app being removed from k8s, I would like to highlight that if we have a PR(in the app config repo) in which one commit contains `prune:false` and another commit has the changes related to removing the app, it will leave the app running because flux syncs all commits in order. Syncing `prune:false` first, will make the app remain alive and the second commit will remove the automation of that app. But if this PR gets "squash and merged" it won't work (Maybe we want to specify this in the docs).

**Comment by jpellizzari** [comment]
@josecordaz Let's scope this down to not include the `--remove-workload` flag for now. We can figure out how to do `remove-workload` later.

**Comment by josecordaz** [comment]
no problem

**Comment by rokshana-b** [comment]
Application can be removed with and without PR

﻿![image](https://user-images.githubusercontent.com/76788247/145343867-45687dfe-8f64-4b7d-97dd-a14ad578a086.png)

![image](https://user-images.githubusercontent.com/76788247/145343805-9d0ceb08-2619-4efe-954d-ba0e39a47d16.png)

![image](https://user-images.githubusercontent.com/76788247/145341693-d4aca77a-f473-4e14-9f21-c0ff65819122.png)
﻿﻿﻿﻿﻿
