### ISSUE TITLE
Write up k8s Client

### ISSUE THREAD

**Issue by JamWils** [weaveworks/weave-gitops#2623]
Can we get a write up about the current k8s client we are using in our codebase, the challenges it is bringing, as well as alternatives we can use to alleviate our namespace headaches.

**Comment by ozamosi** [comment]
There's 2 clients for k8s in go:
* The one simply called `client-go`
* The one from `controller-runtime`.

`controller-runtime` is ultimately a wrapper around `client-go`, which exposes a slightly reduced surface area, but does so in a way that lets it throw in bells and whistles that are good for writing controllers. This is hand-wavy, but I can't see `controller-runtime`'s documentation discuss this
.

A controller is a long lived process that is constantly looking at approximately the same dataset, whereas "not a controller" is often shorter lived, and can query more or less arbitrary data. As an example, `controller-runtime` throws in free, transparent caching when the connection is reused.

Since weave gitops runs queries as the user that sent each request, weave gitops' connections are short lived, and query more and more kinds of data. Because the connection is set up per request, we do not get any caching.

The choice to use : 
* Cross-namespace querying - there's no restriction in etcd or k8s in being able to run a query across all namespaces, but `controller-runtime` does not allow that - I'm going to guess it has to do with the caching, but I haven't found anything definitive. We have a lot of complex and frankly quite scary code to cache namespaces, which wouldn't be necessary if we just used `client-go`.
* The `discovery` API from client-go is not exported in `controller-runtime`, so we can't get the currently running version of k8s without using `client-go`. So we already have to use both clients.
*

**Comment by chanwit** [comment]
>  I'm going to guess it has to do with the caching,

Correct. It uses the namespace-based informers to watch and cache frequently-used objects.

**Comment by chanwit** [comment]
> I would suggest a spike to see how much would need to change if we were to change to client-go.

I would also suggest trying "dynamic-client." Its APIs return unstructured objects and unstructured lists, so it's likely to be somewhat compatible with our current code bases.

Here's an  example:
```golang
	pods, err := dynClient.Resource(
		schema.GroupVersionResource{Group: "", Version: "v1", Resource: "pods"},
	).Namespace("").List(context.TODO(), metav1.ListOptions{
		LabelSelector: "app=kustomize-controller",
	})
```

**Comment by ozamosi** [comment]
Is that this one? https://pkg.go.dev/k8s.io/client-go/dynamic Or is it another one that's not part of client-go?

**Comment by chanwit** [comment]
Yes, that one.

**Comment by ozamosi** [comment]
This doesn't apply when a user doesn't have cluster-level permissions. K8s doesn't do per-namespace filtering when you make a request for "all namespaces" - it simply checks if you have cluster level permissions. As a result, we can't assume we can do one request for all namespaces, unless we check your permissions first.
