### ISSUE TITLE
SPIKE: Create some files for gitops run bootstrapping

### ISSUE THREAD

**Issue by JamWils** [weaveworks/weave-gitops#2635]
The bootstrapping process for gitops run hurts.  Let's create the files that we think will be outputted by the command in the following scenarios.  We will then use those files to drive the stories for making the command work as expected.

The files should contain
1. Flux bootstrap files
2. Gitops dashboard
3. Normal kustomization.yaml (not Flux Kustomization) that follows best practices.
4. Files or configuration to point to the path in `gitops run`

#### Scenario 1 - Root directory and current working directory are the same.
Root directory: /Users/myself/my-repo
Current working directory: /Users/myself/my-repo

#### Scenario 2 - Root directory and current working directory are different.
Root directory: /Users/myself/my-repo
Current working directory: /Users/myself/my-repo/manifests

#### Scenario 3 - Root directory and current working directory are different and the working directory is an application path.
Root directory: /Users/myself/my-repo
Current working directory: /Users/myself/my-repo/apps/podinfo

I run `gitops run .`

I run `gitops run ./workload` <- This is assumed not to exist

I run `gitops run ./deploy/overlays/dev`

**Comment by ozamosi** [comment]
I haven't created the exact full grid, but there's sufficiently many examples to get going.

### General notes

* The exact version of flux used isn't important
* The flux files have to be generated using `flux bootstrap`, which limits what we can do with them
* The exact version of gitops dashboard installed isn't important
* I've not created the implied `kustomization.yaml` files (e.g. `clusters/my-cluster` doesn't have a `kustomization.yaml`). I decided not to, since the flux example repos do not, and I remember past bugs when files are generated but `kustomization.yaml` isn't updated. I could be convinced we should.
* I've created a flux kustomization, not a k8s kustomization, to include the workload. This is a bit unusual, but demos our dashboard better since the workload is now its own thing you can look at. I've reused the flux-system source for this kustomization.

### gitops run .

Scenario 1: https://github.com/ozamosi/scenario-1-gitops-run-dot
Scenario 2: https://github.com/ozamosi/scenario-2-gitops-run-dot

Note:
* We do not create a workload level kustomization, because the path already exists.
* Because the user is explicitly saying that the entrypoint for the workload is at the current top level, this will confuse flux and the resources defined in `clusters/my-cluster/flux-system` will flap between being owned by `flux-system` and `workload`. You don't want to do this.
* I assume we create a `root` special case for the resource name.


### gitops run ./workload

This is the "normal" getting started scenario.

Scenario 1: https://github.com/ozamosi/scenario-1-gitops-run-workload
Scenario 2, but assumed to be `gitops run ../workload` instead of `./workload` (otherwise it'd just be the same as scenario 1 but in a directory): https://github.com/ozamosi/scenario-2-gitops-run-dotdot-workload 

We create the directory `workload` and we create an empty (k8s) kustomization.yaml for the user to get started with.

### gitops run ./deploy/overlays/dev

Someone has set up a bit of automations already, but the user still needs to bootstrap this cluster. 

Scenario 1, using podinfo as the existing repo: https://github.com/ozamosi/scenario-1-gitops-run-deploy-overlays-dev

This is really the same as `./workload` except we don't create any new files in the workload directory because the destination already exists.

### Scenario 3
Using podinfo as a base, and for simplicity's sake I used `deploy/webapp` instead of `apps/podinfo` so it exists.

gitops run .: https://github.com/ozamosi/scenario-3-gitops-run-dot
gitops run deploy/overlays/dev: https://github.com/ozamosi/scenario-3-gitops-run-deploy-overlays-dev

This is probably not what I wanted - now the cluster definition lives under the webapp deploy instructions, and in the second scenario, the user typed a path that they meant to make relative to the root of the repository and we interpreted it as being relative to the root of where they currently are. Disappointing.

However, the user would have had to ignore e.g. tab completion to think that this would work.
