### ISSUE TITLE
SPIKE: 1st v 3rd party helm charts

### ISSUE THREAD

**Issue by JamWils** [weaveworks/weave-gitops#2864]
As a user, I want to work with all things helm, unless I am using kustomize.  I have my own helm charts that we have developed in house, I want to be able to iterate on those and leverage gitops run to get live feedback while working with them.

I also have 3rd-party helm charts that I am using that I want to iterate on and improve.  

How can we have `gitops run` work with both of these instances?

### Acceptance Criteria
Clearly outline with pictures the behavior we would expect when running gitops run in these instances.

Timebox: 8h

**Comment by ozamosi** [comment]
I wrote down some different scenarios.

## Kustomizations
### Simplest case - monorepo
The very simplest case is a monolithic repository containing all of your automations, as kustomizations:
```mermaid
flowchart LR

subgraph local-repository
subgraph /kustomizations
app-namespace.yaml
app-deployment.yaml
app-service.yaml
end
end

gitops-run --> /kustomizations
```
This scenario is easy - all your files are available to you, so you can just edit them.

TODO:
* ✅ It all works
* ✍ Documentation

### Kustomization, 3rd party code
To make it a little bit more complicated, let's assume we want to deploy a pre-existing bundle of kustomizations for podinfo:

```mermaid
flowchart LR

subgraph local-repository
subgraph /kustomizations
subgraph podinfo
namespace.yaml
podinfo-source.yaml
podinfo-kustomization.yaml
end
end
end

subgraph github
subgraph github-podinfo["podinfo"]
podinfo-kustomizations["/kustomizations"]
end
end

gitops-run --> podinfo

podinfo-source.yaml --> github-podinfo
podinfo-kustomization.yaml --> podinfo-kustomizations
```

For this scenario, all resources in `local-repository` are synced by gitops run, and all resources in `github/podinfo`
are synced by flux. This means, you can't interactively edit anything that podinfo ships - you have to set up your local
resources telling flux to patch the upstream podinfo resources.

TODO:
* ✅ All works
* ✍ Documentation

### Kustomization, multiple 1st party repositories 

If I have 2 repositories sitting next to each other (let's say, "weave-gitops" and "weave-gitops-enterprise") and I want to 
make changes to one of them, but I want to see the changes reflected in the other, then we don't really have an answer right
now - you have to run `gitops run` against one repository, and push to a branch in the other repository, and then you're
playing the pre-gitops run sync dance again.

We could make it possible for 2 different repositories to "join" into 1 session, either by doing some kind of
`gitops run --join=<session_id>`, or by specifying multiple repos in a config file. But would we then need each bucket
to go through all other buckets and override all resources there? Would be
cool, but needs someone to have a good idea first.

This isn't inherent to kustomizations - the same scenario can happen with helm charts.

TODO:
* 🤔 Think hard
* ✍ Write TODO list

## Helm chart
### Simplest case - all helm
The very simplest case is a monolithic repository containing all of your automations, as kustomizations:
```mermaid
flowchart LR

subgraph local-repository
subgraph /charts
subgraph /my-app
Chart.yaml
values.yaml
subgraph /templates
deployment.yaml
service.yaml
end
end
end
end


gitops-run --> /my-app
```

In this scenario, we can detect that we were pointed to a helm chart directory, and if so create a helmrelease instead of a
kustomization. The source controller supports building helm release artifacts from sources in buckets (yes, I tested).

Because we're now entirely in the helm universe, we don't actually have to know anything about what helm charts reference 
what other helm charts - if a helm chart specifies a dependency, then it will work like a regular helm dependency.

TODO:
* ✍ Create helm release when gitops run is pointed at a helm chart
* ✍ Documentation

### Multiple 3rd party helm charts
If you want to install multiple 3rd party charts that are not referencing each other - perhaps you want to use `dependsOn` between them - then we can tell you to use the same trick we used for multiple 3rd party kustomizations: create a kustomization, and install the helm releases from there.

```mermaid
flowchart LR

subgraph local-repository
subgraph /kustomizations
podinfo-helmrepository.yaml
podinfo-helmrelease.yaml
other-app-helmrepository.yaml
other-app-helmrelease.yaml
end
end

subgraph ghcr
subgraph github-podinfo["podinfo/charts"]
podinfo
end
subgraph github-other-app["other-app/charts"]
other-app
end
end

podinfo-helmrepository.yaml --> github-podinfo
podinfo-helmrelease.yaml --> podinfo
other-app-helmrepository.yaml --> github-other-app
other-app-helmrelease.yaml --> other-app
```


### 1st and 3rd party helm charts at once
So in the past scenarios, we've suggested that you can work directly on a helm chart in a git repository, and that you can install multiple helm charts by wrapping everything in a kustomization. What happens if you want to do both? E.g., you have a helm chart in your repository, but you also have 3rd party charts you install with `dependsOn`?

```mermaid
flowchart LR

subgraph local-repository

subgraph /kustomizations
subgraph kustomization-podinfo["/podinfo"]
podinfo-helmrepository.yaml
podinfo-helmrelease.yaml
my-app-source.yaml
my-app-helmrelease.yaml
end
end

subgraph /charts
subgraph /my-app
Chart.yaml
values.yaml
subgraph /templates
deployment.yaml
service.yaml
end
end
end

end

subgraph ghcr
subgraph github-podinfo["charts"]
podinfo
end
end

podinfo-helmrepository.yaml --> github-podinfo
podinfo-helmrelease.yaml --> podinfo
my-app-helmrelease.yaml --> /my-app
```
Note that `my-app-source.yaml` doesn't actually link to anything, because I'm not sure how we should do that - if this kustomizations directory is used for permanent dev environments outside of gitops run then it might be a git repository, but inside gitops run it'd be a bucket - but it's the bucket we created dynamically in gitops run.

We could for example dynamically rewrite the automations our users upload to replace the source with a bucket source - but we'd need some indicator that it's the correct source.

This scenario isn't inherent to helm releases - you also can't use a flux-kustomization to point at a different directory in
the same repository, but there the workaround is to just use a k8s-kustomization.

TODO:
 * 🤔 Figure out how to reference resources in the same bucket
 * ✍ Document that it's likely you want a top-level kustomization to reference your helm charts from.

## Conclusion
We can support helm "source" charts easily. We can help our users by documenting patterns and recommendations to solve many common scenarios.

However, we're left with 2 annoying scenarios:
* Multiple repositories with resources you want to sync and edit in the same session
* Multiple directories in the same repository which you are (already?) referencing using flux resources

You can create both these scenarios with both kustomizations and helm releases, and I think we need further work to make them smooth.

**Comment by ozamosi** [comment]
For both scenarios, the most straight-forward solution is to
 * Define an interface for referencing the specific dev bucket(s)
 * Lean into the overlay pattern

I.e. right now the dev bucket is always called `dev-bucket` as an implementation detail - if it was possible to name uniquely and in a documented, stable way (whether from a config file, or by using `dev-bucket-${gitreponame}` or something), then we could simply say that you can check in one overlay for your permanent dev cluster and one overlay for gitops run - and the gitops run overlay would reference the bucket sources. This would also make the idea to join sessions work, without it being too painful.

So, in other words, you don't run `gitops run ./kustomizations` but rather `gitops run ./kustomizations/gitops-run` whereas your dev cluster uses `./kustomizations/dev-cluster`. `./kustomizations/gitops-run` would specify that the sources live in `Bucket/dev-bucket-myapp` unlike `./kustomizations/dev-cluster` which specifies a git repository/oci registry/whatever. If you need to insert multiple repositories, you give the session the same name in all, and they'd just install themselves into the same session.

This would be quite faffy to get going and a bit confusing to get your head around. However, it would be low on magic and low on things to go wrong so it'd be relatively easy to build on and extend in a normal flux way.
