### ISSUE TITLE
GitOps Run cannot detect Enterprise Dashboard

### ISSUE THREAD

**Issue by JamWils** [weaveworks/weave-gitops#2891]
As an enterprise user when I am using `gitops run` it is always asking me if I want to install the dashboard.  This feature should be able to detect when I have the enterprise dashboard installed and not ask this question.

**Comment by opudrovs** [comment]
Created a prerequisite issue https://github.com/weaveworks/weave-gitops/issues/3337

Will use the same code/principle to detect the enterprise dashboard.

Moved the second part of this ticket

>It should port-forward the enterprise dashboard, so it's consistent with what happens when we find an installed OSS dashboard.

to 

https://github.com/weaveworks/weave-gitops/issues/3338

because it requires modifying the port-forwarding functionality which is separate from dashboard detection.
