### ISSUE TITLE
GitOps run table view

### ISSUE THREAD

**Issue by josefaworks** [weaveworks/weave-gitops#2898]
As a user with GitOps Run already running, I would like to see a list of clusters where it is running so that I can see more details and dive deeper if I want. 
In the list of clusters I would also like to see
- the name of the cluster
- how long it has been running (duration) (no filter)
- automation
- source
- CLI version
- port forward (no filter)
- commands used (no filter)

Note: this is enterprise only

Figma link: https://www.figma.com/file/IVHnM9iyeFWpd11evtY8ux/Weave-GitOps?node-id=11227%3A53921

![Screen Shot 2022-10-17 at 10.13.56 AM.png](https://images.zenhubusercontent.com/6138b1b3d7038f238a0ab7fb/fcddb173-a014-43ba-9bf1-9d7c78cca71a)
![Screen Shot 2022-10-17 at 10.13.50 AM.png](https://images.zenhubusercontent.com/6138b1b3d7038f238a0ab7fb/4ffdc73f-1db2-47b0-9753-acb50732a3d4)

**Comment by ozamosi** [comment]
The implementation of sessioned and unsessioned mode would have to be separate. Let's start with sessioned mode (because otherwise you can't have more than one, and then it's not much of a list).

We should define a "session" as "HelmRelease with the labels `app.kubernetes.io/managed-by=GitopsRun` and `app.kubernetes.io/component=session`". These labels aren't currently set, we need to set them automatically.

We should store the other bits of information given to the CLI we want to display - cli version, port-forward, command, bootstrap, dashboard - as annotations. These annotations can be prefixed by `run.weave.works' so e.g. the annotation `run.weave.works/cli-version=0.9.2-rc.2` would print that CLI version field.

We can't link to automation or source in session mode right now, so skip that. This needs further work to connect to inside the vcluster.

**Comment by ozamosi** [comment]
From #2907 session metadata, we get:
* the name of the cluster
* CLI version
* port forward (no filter)
* commands used (no filter)

To add:
* how long it has been running (duration) (no filter) - this is the age of the statefulset

Moved to weaveworks/weave-gitops-enterprise#1772, skip in this ticket:
* automation
* source

**Comment by ozamosi** [comment]
We don't have anywhere to link the name to yet - don't link it.

**Comment by ozamosi** [comment]
Add the ability to filter by label to listObjects, and make the call to the backend include the labels added in #2907
