### ISSUE TITLE
Chang 'TYPE' column to 'KIND'

### ISSUE THREAD

**Issue by bia** [weaveworks/weave-gitops#2927]
**Short description**
It might make more sense if the column title `TYPE` of our ui actually matched the yaml language, which is KIND

**Acceptance criteria**
Rename TYPE to KIND in the following tables:
- [ ] Applications
- [ ] Applications > Details (table of reconciled objects
- [ ] Sources
- [ ] Sources > Details (summary info)
- [ ] Sources > Details (table of related applications)

Note for OCI Helm Repositories, we can still rename Type to Kind, but should keep the Repository Type field.
<img width="459" alt="Screenshot 2022-11-03 at 10 06 41" src="https://user-images.githubusercontent.com/19860021/199693966-734d9310-dd5a-4cb5-887b-8b60dc333f09.png">

**Comment by sympatheticmoose** [comment]
@bia just since in the original description the figma reference is for Templates in Enterprise - I think thats the one place in the UI where type is more applicable than Kind ;) In the case of templates, they'll always be `kind: GitOpsTemplates` but we're differentiating based on the label `weave.works/template-type:` (note - type).

In the OSS tier I agree this makes more sense and I've updated the scope to cover applications and sources (and their sub-pages). We'll need to do a quick sizing to understand whether this is something we want to tackle right now.

**Comment by sympatheticmoose** [comment]
@jpellizzari do you have a gut feel on the relative effort required for this change?

**Comment by jpellizzari** [comment]
0.0001 Story Points. Let me see if I can do it without opening my editor.
