### ISSUE TITLE
Add calculating the Unknown object state and displaying the appropriate indicator icon for it

### ISSUE THREAD

**Issue by opudrovs** [weaveworks/weave-gitops#3289]
Based on discussing https://github.com/weaveworks/weave-gitops/issues/3238 with @chanwit and @joshri 

Acceptance Criteria:
- [ ] Add support for calculating and displaying  the `Unknown` object state in the `KubeStatusIndicator` and possibly `PageStatus` components.

Questions for refinement:
- Check the criteria for deciding that an object is in the Unknown state. Is the `Unknown` state the same as the `NotReady` state which is already calculated? Should we add calculating the new state or just keep the old NotReady state?
- Is it OK to display a hourglass icon for an object in the Unknown state. Does the Unknown state of an object always mean that we are waiting in the UI for some action to complete?

**Comment by joshri** [comment]
SO - we support the `Unknown` status when the `Reason` condition type has a value of `Progressing`. In this scenario we display the blue reconciling icon. Otherwise you're gonna get the `Not Ready` treatment. In standup today @chanwit mentioned that this SHOULD work for Terraform objects, so we should actually already be seeing things reconcile on the 5 second poll if you hit the plan button. If this is not what's already happening then we need to figure out why!!

**Comment by joshri** [comment]
As discussed in standup, we are good with the existing reconciling state and icon for the tf-plan tab! Closing

**Comment by chanwit** [comment]
Closed with rhyme.

```
Verse 1:
Throwing the hour glass icon away,
I do not want it to stay,
Ticket closed with a final decree,
Best fix, as you can clearly see.

Chorus:
Goodbye to the hour glass, it's time to part,
My wish, from the bottom of my heart,
No more waiting, no more delay,
With this fix, a brighter day.

Verse 2:
No more frustration, no more delay,
With this fix, I can now say,
That my troubles have been alleviated,
And my worries have been mitigated.

Chorus:
Goodbye to the hour glass, it's time to part,
My wish, from the bottom of my heart,
No more waiting, no more delay,
With this fix, a brighter day.
```
