### ISSUE TITLE
Add wego app list via cli

### ISSUE THREAD

**Issue by palemtnrider** [weaveworks/weave-gitops#337]
**Short description**
As a wego user I want to list deployed apps so that I can manage my gitops environment.

`wego app list` will list deployed apps in the cluster. 

Applications list. 

Define what we show for each app, start with the name so folks can use it -- start with just the name.  On the UI you can click through to get an app status page with more details.   On the CLI you can use app status.

**Comment by jpellizzari** [comment]
Assigned to @josecordaz (on his request ;)).

We discussed implementation and are going to try using either of these two client libraries (rather than `kubectl`):

https://github.com/kubernetes/client-go

or maybe the controller-runtime client:

https://github.com/kubernetes-sigs/controller-runtime/tree/master/pkg/client

@palemtnrider , @jrryjcksn any thoughts on which client library to use? ^^

Here is how I originally did it for WebUI: https://github.com/fluxcd/webui/blob/main/pkg/util/util.go

**Comment by jpellizzari** [comment]
Some more implementation notes from slack:

`if we create an app called called my-app, there'll be in the cluster a GitRepository and Kuztomization|HelmRelease called my-app`

**Comment by jpellizzari** [comment]
Controller runtime List code example: https://github.com/fluxcd/webui/blob/main/pkg/clustersserver/clustersserver.go#L226
