### ISSUE TITLE
Better structured paid tiers

### ISSUE THREAD

**Issue by aabmets** [weaveworks/weave-gitops#4052]
**Problem**

Weaveworks only offers two versions of their software: OSS and Enterprise. With the first variant, you get minimal features which can't be used for pretty much anything useful. The enterprise variant is the full-blown 3000 USD-a-month behemoth for managing entire clusters. Why isn't there a middle ground version, which would offer some features from the enterprise version, but for managing a single app in a kubernetes cluster, much like the OSS version offers? To be specific, I want to use the progressive delivery feature of the enterprise version to only manage a single app, not the whole cluster. The OSS version is only useful for handling resource reconciliation and not much else, which makes it mostly useless. There is a middle ground here to be realized, which Weaveworks can also profit from.

**Solution**

Create a middle ground variant of the weave server that caters to a single app in a single namespace, that would offer some features from the enterprise version, namely the progressive delivery feature.
You could even structure the pricing such that using multiple licenses for this variant would become more expensive than buying the full enterprise variant. 

**Additional context**

Your pricing should be more transparent about how exorbitant it is.

**Comment by mestadler** [comment]
Hi Mattias, We actually do have tiers that may be of interest to you.  The enterprise version is $1500 per month before discounts, and half that for dev systems.  With Assured, we do offer flagger support, there is a UI, that you can add to the UI.  I would love to chat with you, first to see how we can make this more transparent, and secondly to get your feedback on what you would like to see for tiering.

Martin SVP CX

**Comment by aabmets** [comment]
@mestadler 
I decided to remove Weave Gitops from our organization project, because Weave Gitops is incompatible with being single-namespace-specific only, for a single app. It demands too many cluster-wide permissions and a production-grade OIDC integration with GitHub is a pain in the ass to implement correctly, partly due to lack of documentation on Dex and on Weaveworks part (your docs reference legacy dex versions). The marginal added benefit of OSS Weave Gitops is not worth the pain it requires to get working correctly. Maybe that's why Weaveworks has the Assured and Accelerator tiers? Anyway, not worth the cost.

**Comment by makkes** [comment]
@aabmets thanks so much for your feedback! I'd like to respond to some of your issues to help you contextualize Weave GitOps and how it works:

1. "Weave Gitops is incompatible with being single-namespace-specific": Is your goal to install Weave GitOps in a way that it only shows applications from a single namespace? Weave GitOps is built to be installed by cluster administrators so it is usually installed with privileges to query the whole cluster for applications (as you can see the default RBAC rules are read-only). Users accessing Weave GitOps then authenticate with their credentials and the RBAC rules specific to their account are applied. These can very well be targeted to a single namespace.
2. "a production-grade OIDC integration with GitHub is a pain in the ass to implement correctly, partly due to lack of documentation on Dex and on Weaveworks part.": While I certainly agree that the documentation around OIDC setup can be improved I want to stress that neither Dex nor GitHub are mandatory to access Weave GitOps. You're free to use any OIDC provide that best fits your use case and environment. On-premise solutions like Keycloak work very well, too.
3. "your docs reference legacy dex versions": We should fix that, thanks for pointing this out! Again, the documentation only provides examples. As you surely know, each environment is different so we can't provide specific instructions for each particular situation.
4. "Maybe that's why Weaveworks has the Assured and Accelerator tiers": Different tiers unlock different capabilities and different service levels.

Again, thanks for the feedback and taking Weave GitOps for a spin.
