### ISSUE TITLE
Wego fails to add 2 different apps from the same helm-repo url

### ISSUE THREAD

**Issue by rokshana-b** [weaveworks/weave-gitops#485]
**Describe the bug**
Wego fails to add multiple charts from the same helm-repo. Although the url is same, user should be able to add different apps from the same repo without seeing any errors.

**Environment**
 - wego: [v0.2.0]
 
**To Reproduce**
1. Download wego with the latest changes
2. Run `wego gitops install`
3. Run `wego app add --url=https://charts.bitnami.com/bitnami --chart=nginx --app-config-url=<>`
4. Observe the nginx app get added to the cluster with `wego app list`
5. Run `wego app add --url=https://charts.bitnami.com/bitnami --chart=tomcat --app-config-url=<>`
6. See `Error: failed to add the app : unable to create resource, resource already exists in cluster`

**Screenshots**

![image.png](https://images.zenhubusercontent.com/606389351ead0c83798a9a73/e2900291-6c91-4a73-9c1b-32a6c9fede20)

**Comment by luizbafilho** [comment]
I would go a little bit further, in helm case, one should be able to install the same chart multiple times, as long they have different names.

**Comment by jrryjcksn** [comment]
So, it looks like the issue is that the app hash is always being computed based on `url/path/branch` even in the helm case. It should use `chart` rather than `path` for helm repositories.

I'm not sure about installing the same chart multiple times w/ different names; in the external repo case, I believe that would mean multiple apps would be referencing the same GOAT and changing one would affect them all.
