### ISSUE TITLE
Spike: Show the commits for an application branch

### ISSUE THREAD

**Issue by jpellizzari** [weaveworks/weave-gitops#514]
The commits of a application config effectively represent different versions of the application. Users will eventually want to select different versions to apply to their cluster. The first step in that process will be listing the commits for their repo.

Important information to show about commits:
* Short hash
* Author
* Message
* Date

Balsamiq Link: https://balsamiq.cloud/s5qd59g/p340wpr/rA93F

Notes:
* This probably doesn't fit into into the `app status` command output as it is right now. Do we need an `app describe`? Or should we reformat the `app status` output?

* Commits will need to be returned in the `GetApplication` API response.

* How do we track if a user changes the `Branch` in the `Application.Spec`?

* Clone or Git Provider APIs (auth)?

Spike output: Enumerate the concerns and trade-offs of starting this work

**Comment by jpellizzari** [comment]
@josecordaz Would you mind pasting in any docs you found on clone a repo with history only?

**Comment by J-Thompson12** [comment]
- This probably doesn't fit into into the app status command output as it is right now. Do we need an app describe? Or should we reformat the app status output? 
I believe that app status should remain how it is where it is clean and concise.  I dont really think a list of commits makes sense to be in status. I believe creating its own command allowing users to determine the number of commits to return (good for large projects) would be a better option. If we mix it in with status it will be hard to let people know it is there. Better to be clearer with the user than just trying to fit it somewhere.

- How do we track if a user changes the Branch in the Application.Spec?
For commits I dont really see this as an issue because we can just get the branch from the application spec using kubehttp then get the commits for that branch. The real issue is we base wego-label off the branch as well. We are not handling the change of a branch name there. The easiest way to handle both problems as well as the inclusion of the UI is to have a command to change the branch that way we can update the label and check for existing resources with the branch/path/url.

- Clone or Git Provider APIs (auth)?
go git providers allows getting a list of commits using a ListPage function. The issue with this method is that all the information provided is the commit hash. If we could talk to the flux team and get more information returned but this may require more time than we want. It seems like the best path here is to clone the repo.

**Comment by J-Thompson12** [comment]
Here is some information on cloning a repo with history. There are two options bare works for this but mirror was interesting so I am including it. 


git clone --bare
Similar to git init --bare, when the -bare argument is passed to git clone, a copy of the remote repository will be made with an omitted working directory. This means that a repository will be set up with the history of the project that can be pushed and pulled from, but cannot be edited directly. In addition, no remote branches for the repo will be configured with the -bare repository. Like git init --bare, this is used to create a hosted repository that developers will not edit directly.

git clone --mirror
Passing the --mirror argument implicitly passes the --bare argument as well. This means the behavior of --bare is inherited by --mirror. Resulting in a bare repo with no editable working files. In addition, --mirror will clone all the extended refs of the remote repository, and maintain remote branch tracking configuration. You can then run git remote update on the mirror and it will overwrite all refs from the origin repo. Giving you exact 'mirrored' functionality.

**Comment by josecordaz** [comment]
Huge favor @J-Thompson12 could you please test both bare and mirror options with this repo https://github.com/django/django to see which one is faster?

**Comment by jpellizzari** [comment]
> I believe that app status should remain how it is where it is clean and concise. I dont really think a list of commits makes sense to be in status. I believe creating its own command allowing users to determine the number of commits to return (good for large projects) would be a better option. If we mix it in with status it will be hard to let people know it is there. Better to be clearer with the user than just trying to fit it somewhere.

@J-Thompson12 What command would you recommend we implement for this?

> For getting commits I dont really see this as an issue because we can just get the branch from the application spec

SGTM

> It seems like the best path here is to clone the repo.

Do we clone the repo every time someone runs the command to list commits? If not, where do we store that cloned repo and does it get cleaned up?

> If we could talk to the flux team and get more information returned but this may require more time than we want

We can do this work ourselves or possibly fork the repo for our purposes. An HTTP call to fetch commits fits better into our API-driven approach. Does `go-git-providers` use HTTP to fetch commit data?

**Comment by josecordaz** [comment]
> - Clone or Git Provider APIs (auth)?
go git providers allows getting a list of commits using a ListPage function. The issue with this method is that all the information provided is the commit hash. If we could talk to the flux team and get more information returned but this may require more time than we want. It seems like the best path here is to clone the repo.

@J-Thompson12 for this option I think there is a field that contains the raw api call output. The information you are looking for might be there. This is an example https://github.com/fluxcd/go-git-providers/blob/main/github/integration_test.go#L239 more specifically `.APIObject()`

> Does `go-git-providers` use HTTP to fetch commit data?

@jpellizzari yes it does, it uses go client for github. https://github.com/fluxcd/go-git-providers/blob/main/github/githubclient.go#L311

**Comment by jpellizzari** [comment]
> for this option I think there is a field that contains the raw api call output

@josecordaz I think the question is more about process than the data being returned. We don't *own* that project, and in the even that the maintainers do not wish to add the changes that we need (for whatever reason), we need to come up with an alternative.

From what I can tell, adding more data to the `Commit` struct should be easy, but that may not be a change that the maintainers want to make.

**Comment by J-Thompson12** [comment]
> We can do this work ourselves or possibly fork the repo for our purposes. An HTTP call to fetch commits fits better into our API-driven approach. Does go-git-providers use HTTP to fetch commit data?

@jpellizzari I agree that doing an http option would be better. However if we are unable to get flux to implement the change then we are left with two choices. Clone using bare or support it all ourselves(write it ourselves or fork go-git-providers). 

> Do we clone the repo every time someone runs the command to list commits? If not, where do we store that cloned repo and does it get cleaned up?

Since we would do a bare clone then cloning it each time a command is run wouldnt be too much of a hassle but saying that feels like someone is gonna come in with an absolutely massive repo and prove me wrong. 

> What command would you recommend we implement for this?

this depends on the solution we end up going with. Seeing as we need to handle changing the branch in the label it may not be a horrible option to have repo specific commands something like `wego app set-branch nginx` `wego app get-commits nginx`  or maybe even more generic and call it something like `wego app info` if we need to get more specific than that we probably should. I just really feel like status is a super weird place to put commit info and its too much info to clutter something as important as status.

I figure the label stuff can be handled another time and I plan on writing up an issue for it so we can make the best decision on it so if we decide to not do that

**Comment by josecordaz** [comment]
> @josecordaz I think the question is more about process than the data being returned. We don't *own* that project, and in the event that the maintainers do not wish to add the changes that we need (for whatever reason), we need to come up with an alternative.

> From what I can tell, adding more data to the `Commit` struct should be easy, but that may not be a change that the maintainers want to make.

> It's also entirely possible the maintainers say "yeah sure no problem", and we are good to go.

I completely agree, just wanted to clarify that it is possible to get the information we need using the raw field(without modifying go-git-providers) which we already have access to, (in case we choose to take this path), this is an example:
![image.png](https://images.zenhubusercontent.com/606389311ead0cc4788a9a72/560fe52a-91b1-4462-ad17-5cfbff300d75)

**Comment by jpellizzari** [comment]
> just really feel like status is a super weird place to put commit info and its too much info to clutter something as important as status.

I agree. Sticking with noun verb, `wego app get-commits` is probably the way to go.

> I figure the label stuff can be handled another time and I plan on writing up an issue for it so we can make the best decision on it so if we decide to not do that

Yeah it seems like an issue no matter what we do. Even if we do nothing, someone changing the `Spec.Branch` is a problem.

> it is possible to get the information we need using the raw field(without modifying go-git-providers) 

@josecordaz Ah OK I understand now. Very cool. 

@J-Thompson12 I think we should plan on doing HTTP via `go-git-providers` for now (since it seems to be do-able based on @josecordaz 's info), and if we hit a blocker, revert to cloning. WDYT?

**Comment by jpellizzari** [comment]
@J-Thompson12 One last deliverable for this that I forgot to enumerate: Please include some design notes on how the WeGO HTTP API will be structured.

**Comment by J-Thompson12** [comment]
Okay to sum up this spike
 - It will be best to do a specific command to get commits instead of tossing it in with status and cluttering up important info
- talk with flux to see if go-git-providers can return more data on commits if not then we need to fork it or bare clone the repo
- grab the branch from the application spec using kubehttp. Worry about changing branches for other projects that will have problems with the change.

The grpc structure
```
message commit {
    string   commit_hash                            = 1;  // The hash of the commit
    string   author                            = 2;  // The author of the commit
    string   date                             = 3;  // The date the commit was made. the date type is subject to change.
    string commit_message     = 4;  // The commit message
}

message ListCommitsRequest {
    string namespace = 1;  // The namespace the application is in
    string name = 2;  // The application name
}

message ListCommitResponse {
   repeated Commit commits = 1; // A list of commits
}
```

**Comment by jpellizzari** [comment]
LGTM :+1:

One think to keep in mind is that we will need to include some pagination metadata in both the request and response body. No need to figure out exactly how that works here, but just wanted to keep it in mind.

**Comment by jpellizzari** [comment]
Re-opening. We haven't discussed as a group yet.

**Comment by jpellizzari** [comment]
Tasks:

* Go-git-providers change
* Fetch last N commit
* Add pagination

**Comment by jpellizzari** [comment]
Implementation issues created. Nice work on this @J-Thompson12
