### ISSUE TITLE
Create "wego update" command

### ISSUE THREAD

**Issue by jrryjcksn** [weaveworks/weave-gitops#627]
**Short description**
As a Weave GitOps user, I want to upgrade my existing Weave GitOps installation to the latest version.

**Acceptance criteria**

**Given** a new wego binary with version X.Y.Z
**And** a Weave GitOps installation running version >= X-1.0.0
**When** I invoke the `upgrade` command for the new binary
**Then** A PR is created in the platform repository containing the new GORT manifests
**And** the cluster is updated to the new version when the PR is merged

This assumes that none of the CRs generated during `wego app add` have been modified. If/when that occurs, we will need to update those in all relevant config repositories. See: Issue #70. 

**Design materials**
https://app.zenhub.com/workspaces/weaveworks-foss-603cb6b1d4dff9000e242dc4/issues/weaveworks/weave-gitops/70

**Comment by sympatheticmoose** [comment]
A point on terminology - it would be useful for us if this could be `update` rather than `upgrade`. If we want to provide a CLI experience for upgrading from Weave GitOps Core to Weave GitOps Enterprise, `upgrade` is likely to make the most sense. So upgrade is to the higher tier, update is to the higher version.
