### ISSUE TITLE
Figure out the work it would take to add a path to upgrade from Flux to WeGO

### ISSUE THREAD

**Issue by jpellizzari** [weaveworks/weave-gitops#767]
If a user has an existing cluster with Flux installed and running, we should provide an easy way for them to upgrade to `wego`. This could be a large adoption driver for the WeGO project. Ideally, this would be a single command.

UX: Flux cluster -> `wego <some command>` -> WeGO cluster

I don't think it will be possible to "detect" applications, but maybe a cluster that is equivalent to the `gitops install` end state would be enough. That would give the user:
* The ability to do `gitops app add`
* A browser UI

Possible spike outcomes:
* One or more issues that encapsulate the work that would be required to make this happen
* A PoC implementation

Edit: Converting this into a task.

The steps to get this done are roughly:

1. Detect if flux has been installed and if it has, skip installing controllers
2. Add a gitops toolkit version validation in the install command to make sure the installed components meets WeGO requirements (includes validating for necessary controllers via their respective CRDs)
3. Document how to manually migrate current flux manifests to wego repository so we can manage flux
4. The files that are generated on `gitops install` need to match what is generated by `flux bootstrap`

**Comment by jpellizzari** [comment]
Can we just install into `flux-system`? (get rid of `wego-system`)

**Comment by sympatheticmoose** [comment]
I tried this, CLI appears to work but is a pain having to add --namespace against every command. We should chat to the Flux folks and agree a way that this can be stored as config/env var. UI doesn't work due to https://github.com/weaveworks/weave-gitops/issues/816

**Comment by palemtnrider** [comment]
@sympatheticmoose Do we need to support going back to just flux managed?  Or starting with GitOps and wanting to go to just a flux-managed cluster?

**Comment by luizbafilho** [comment]
There is nothing special about Weave Gitops's Flux deployment, so to make wego to use an existing deployment of Flux, we need to avoid installing the Flux runtime when we install Weave Gitops onto a cluster.

After that, everything should work as expected without any other intervention.

Caveats to this approach: 
- We need to make the running version of Flux runtime compatible with the Gitops version the user is installing and/or upgrading. 
	- This includes validating the list of required components that need to be deployed since you can run just a subset of the Gitops Toolkit and all its versions.
- The user is solely responsible for maintaining and upgrading its Flux version.

Taking over a running Flux automatically and managing it as it was Weave Gitops own Flux is quite challenging since there is no way to determine how that deployment was made; it could be using `flux bootstrap` command or customized files that were exported, saved anywhere and manually executed.

So the better way for handling such a situation where the user desires  Weave Gitops to control the Flux runtime is by documenting how they could take their YAML files and drop them in the correct place in WeGo repository so we can manage it.

One of the biggest Pros of the approach is that we are completely isolated from the running Flux, meaning that uninstalling Weave Gitops is much easier and should have no impact on the system.

The steps to get this done are roughly:

1. Add a flag in `gitops install` to indicate the flux runtime should not be installed. ie: `--skip-flux-install` ?
2. Add a gitops toolkit version validation in the install command to make sure the installed components meets WeGo requirements
3. Document how to manually migrate current flux manifests to wego repository so we can manage flux

**Comment by luizbafilho** [comment]
> Additional questions to explore in the spike :
> 
> * [ ]  If the user installed a subset of the flux components -  i.e., using the. --components Do we do anything differently?
> * [ ]  Secrets that may already be in use by flux - do we need to perform any actions?  For example if --token-auth is used when bootstrapping can we reuse that instead of creating deploy keys?

1 - we add a validation step during gitops install.
2 - we don't use flux's secrets and keep creating ours, as usual, that way we and are less invasive.

**Comment by stefanprodan** [comment]
I propose for Weave GitOps Core to detect and require only GitOps Toolkit capabilities. No matter where Flux is installed and how is managed (flux install, flux bootstrap, flux terraform provider, eksctl, EKS Anywhere, Azure Arc, RedHat OperatorHub, D2iQ DKP), we can look for the APIs that WeGo depends on:
- source.toolkit.fluxcd.io/v1beta1
- kustomize.toolkit.fluxcd.io v1beta2
- helm.toolkit.fluxcd.io v2beta2 

Weave GitOps Core could warn users that it's their responsibility to upgrade Flux and keep the controllers versions in a range that WeGo supports (`wego check --pre`). 

I think that telling users to migrate to a WeGo managed Flux it's not feasible on every platform, especially if the platform competes with WeGo like D2iQ DKP. For WeGo Enterprise, we may want to enforce a managed Flux. But for the Core edition, I would allow any Flux user to migrate, without any changes to their clusters. This way, I think we can showcase WeGo's unique capabilities even on clusters bootstrapped with a competitor's solution that embeds Flux.

**Comment by jpellizzari** [comment]
Closing in favor of creating a ticket that encapsulates the work that needs to be done.
