### ISSUE TITLE
What can we borrow from the Weave Cloud Deploy functionality 

### ISSUE THREAD

**Issue by palemtnrider** [weaveworks/weave-gitops#95]
**Question**
What concepts, code, etc can we borrow from the Weave Cloud Deploy functionality?

**Short description**
I've heard from several sources that the deploy functionality is useful for customers of weave cloud.  Because of this, we should inventory what's there and assess what might be brought into WeGO

**Timebox**
1 day

---

**Outcome**
Writeup your findings here.  Please include the following (if any have been created) :
- Screenshots
- Design/architecture diagrams

**Comment by palemtnrider** [comment]
Not specifically the code but the concept of the deploy action

**Comment by palemtnrider** [comment]
@markramm  the Deploy button and the progress are key concepts.

**Comment by markramm** [comment]
Things that are interesting: 

- Deploy button, and deploy progress view
- The timeline view (in phase 4 when we have prometheus

**Comment by jpellizzari** [comment]
Documenting the different stages of the Deploy UI:

Pre button click; this shows which image is currently running on the cluster and which image will be deployed:
![Screenshot from 2021-05-17 10-24-06](https://user-images.githubusercontent.com/2802257/118530964-22642600-b6fa-11eb-9540-de27936e881e.png)

Flux v1 has two stages. The "Sync" stage is doing repository operations. The "Apply" phase is applying the manifest(s) to the cluster. 
![Screenshot from 2021-05-17 10-24-13](https://user-images.githubusercontent.com/2802257/118531037-3740b980-b6fa-11eb-8434-7d65d28b1ac5.png)

Some notifications pop in as things are happening (top right):
![Screenshot from 2021-05-17 10-24-23](https://user-images.githubusercontent.com/2802257/118531149-5fc8b380-b6fa-11eb-953b-af8cbb6d4901.png)


After the process is completed, some notes about the status of the individual steps:
![Screenshot from 2021-05-17 10-24-36](https://user-images.githubusercontent.com/2802257/118531232-7707a100-b6fa-11eb-97bf-f6bb7bab3bd5.png)

**Comment by jpellizzari** [comment]
To me, the core features of the Weave Cloud Deploy UI are as follows, with some added notes about Weave GO feasability:

Weave Cloud Deploy: Show a list of things that can be updated and their current image status
- Weave GO: the list of "things to be updated" might be trivial, but showing the image status or "this thing can be updated" will take some thought, as the data model does not match 1-1

Weave Cloud Deploy: Show what changes will take place when the user clicks "Release"
- Weave GO: Weave Cloud's atomic unit is a container image. Since Weave GO's atomic unit is a set of K8s yamls at a specific version (git ref), things are a little trickier here. We can show the different ref that will get applied, but a deeper diffing UI would take some time. Linking to a commit may be enough, since Github (or whomever) will take care of that UI for us.

Weave Cloud Deploy: Show the status of the steps of a deployment
- Weave GO: Flux v1 had a simpler model where one agent did all the work, and therefore knew the status of that work. Its not immediately clear to me how we could know which things are "in progress". 
- A manual "sync" interaction is easy enough to track (the Flux UI does this now). Maybe we rely on the notification-controller for richer updates. We may also what to take a look at how `kspan` does it.

> The timeline view (in phase 4 when we have prometheus

We do not need prometheus to render at timeline of releases. We *would* need prom for metrics/alerts/other events overlayed on the timeline.

**Comment by jpellizzari** [comment]
In summary:

For a first-iteration of the Weave GitOps UI, Weave Cloud will be the inspiration for much of what we implement via a deployment UI. Weave Cloud is built on Flux v1, and Weave GO will be built on Flux v2, so the differences in the two data models will be where the UIs diverge, with Weave GO being more holistic, where Weave Cloud focused on container image changes.
